# Generated by Django 5.2.4 on 2025-08-13 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='municipality',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nin',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user_type'], name='accounts_pr_user_ty_77c9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['state', 'municipality'], name='accounts_pr_state_6599f8_idx'),
        ),
    ]
