# Generated by Django 5.2.4 on 2025-08-02 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer', '0001_initial'),
        ('seller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedoffer',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller.offer'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='buyer.buyerprofile'),
        ),
        migrations.AddField(
            model_name='acceptedoffer',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyerrequest'),
        ),
    ]
